### ISSUE TITLE
Option to select features for NMF

### ISSUE THREAD

**Issue by ludvigla** [zdebruine/singlet#14]
`RunNMF.Seurat` takes all features available in the normalized data slot. It would be useful with an option to manually select features (e.g. the top variable genes) to speed up the computation.

Does it really make that much of a difference to run the NMF on all genes vs the top variable genes? I'd expect that many of the genes with low variability are either house keeping genes or extremely sparse.

/Ludvig

**Comment by zdebruine** [comment]
@ludvigla I recommend against using only variable features because you lose a significant amount of information, and as a consequence, robustness across replicates and achievable rank.

We need to make some of our benchmarking public, but at one point I benchmarked the robustness of NMF models across batches of experiments using only variable features (n = 2000 or 3000) vs. all features and the results were very significantly better with all features.  Also, tests for variability are fundamentally limited in their ability to handle sparsity/dropout, while NMF handles imputation alongside signal recovery.

**Comment by zdebruine** [comment]
Added support for running NMF on selected features, indices, rownames, variable features, etc. in a716c42ed2cca367dffd1d3b62177b5a4fecced3.  This is not intended to excuse due diligence in finding robust models, so hopefully this makes benchmarking easy for your specific use cases.  Run it both on the full feature set and on your selected feature set, then see how the models compare across experiments or even random restarts.
