### ISSUE TITLE
Corner case of RunNMF trying rank 1

### ISSUE THREAD

**Issue by MarcElosua** [zdebruine/singlet#31]
Hi Zach.

Very cool package, thank you so much for developing it! I was trying it out on a test set and came across a corner case in which the NMF Rank determination tried to test k = 1. Probably doesn't happen very often but maybe worth dealing with it programmatically?

```
> sce <- singlet::RunNMF(sce, split.by = "sample_id")
running with sparse optimization

REPLICATE  1 / 3 
k = 2 , rep = 1 
   test_error = 9.2164e-01 
   not overfit
   best rank in replicate = 2 

k = 3 , rep = 1 
   test_error = 5.7466e-01 
   overfit (overfit_score = 4.1233e-03 )
   best rank in replicate = 2 

k = 1 , rep = 1 
Error: Not a matrix.
```

**Comment by zdebruine** [comment]
Yes, thanks.  Will leave this open until resolved.

**Comment by jemorlanes** [comment]
Do you have any suggestions for potential solutions for this issue? What I have done is, in those objects where I encounter this issue, I manually specify `k` to the number that was deemed best rank in the run that gave the error.

So for example:

`> sce <- singlet::RunNMF(sce, split.by = "sample_id")
running with sparse optimization

REPLICATE  1 / 3 
k = 2 , rep = 1 
   test_error = 9.2164e-01 
   not overfit
   best rank in replicate = 2 

k = 3 , rep = 1 
   test_error = 5.7466e-01 
   overfit (overfit_score = 4.1233e-03 )
   best rank in replicate = 2 

k = 1 , rep = 1 
Error: Not a matrix.`

I see that `k = 2` is the best rank, so I will try again and do:
`> sce <- singlet::RunNMF(sce, split.by = "sample_id", k = 2)`

**Comment by zdebruine** [comment]
Since an NMF model of k = 1 is generally not what we are looking for in automatic rank determination, I have removed it from `ard_nmf`, although it is still available via `run_nmf(..., rank = 1, ...)` and `RunNMF(..., k = 1, ...)`.  See https://github.com/zdebruine/singlet/commit/c98b871cf5540693be49e37bebc80416ff266a37.  Specifically, a k =1 factor model gives weights that can be derived from the difference between both factors in a k = 2 factor model, and as a result provides no additional insights in practice, so why not always use k = 2 if one is willing to consider higher rank?  For things like pseudotime assignment, k = 1 can be useful indeed, but then one wouldn't be doing automatic rank determination.
